/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/TelephonyUI.framework/TelephonyUI
 */

#import "TelephonyUI-Structs.h"
#import "TPBottomBar.h"

@class UIImageView, TPPushButton, UIView;

@interface TPBottomButtonBar : TPBottomBar {
	id _delegate;
	UIImageView* _backgroundView;
	UIView* _well;
	TPPushButton* _button;
}
+(id)_backgroundImage;
-(void)addBackgroundAndWellIfNecessary;
-(id)initForIncomingCallWaitingWithFrame:(CGRect)frame;
-(id)initForVideoIncomingCallWaitingWithFrame:(CGRect)frame;
-(id)initForEndCallWithFrame:(CGRect)frame;
-(id)initForEndVideoWithFrame:(CGRect)frame;
-(id)initForTTYWithFrame:(CGRect)frame;
-(id)initForVoiceControlWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)setButton:(id)button;
-(id)button;
@end

