/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/TelephonyUI.framework/TelephonyUI
 */

#import "TelephonyUI-Structs.h"
#import "TPBottomButtonBar.h"

@class TPPushButton;

@interface TPBottomDualButtonBar : TPBottomButtonBar {
	TPPushButton* _button2;
	unsigned _drawSeparator : 1;
}
-(id)initWithFrame:(CGRect)frame;
-(id)initForIncomingCallWithFrame:(CGRect)frame;
-(id)initForCallFailureWithFrame:(CGRect)frame;
-(id)initForEmergencyCallWithFrame:(CGRect)frame;
-(id)initForVideoChatWithFrame:(CGRect)frame;
-(void)dealloc;
-(float)_buttonWidth;
-(void)_updateButtonSettings:(id)settings;
-(void)setButton:(id)button;
-(void)setButton2:(id)a2;
-(id)button2;
-(void)setDrawsSeparateWells:(BOOL)wells;
-(void)drawRect:(CGRect)rect;
@end

