/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/TelephonyUI.framework/TelephonyUI
 */

#import <UIKit/UIView.h>
#import "TelephonyUI-Structs.h"


@interface TPBottomBar : UIView {
	int _orientation;
}
+(id)_backgroundImage;
+(void)preloadImages;
+(float)defaultHeight;
+(float)defaultHeightForOrientation:(int)orientation;
-(id)initWithDefaultSize;
-(id)initWithDefaultSizeForOrientation:(int)orientation;
-(id)initWithFrame:(CGRect)frame;
-(void)setOrientation:(int)orientation;
-(int)orientation;
-(void)drawRect:(CGRect)rect;
@end

