/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/TelephonyUI.framework/TelephonyUI
 */

#import "TelephonyUI-Structs.h"
#import <UIKit/UIImageView.h>

@class TPBottomLockBar, UIAlphaAnimation;

@interface TPLockKnobView : UIImageView {
	TPBottomLockBar* _track;
	UIAlphaAnimation* _animation;
	float _centerDelta;
	BOOL _tracking;
}
-(id)initWithImage:(id)image;
-(BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
-(void)setLockView:(id)view;
-(void)dealloc;
-(BOOL)shouldBeginTracking:(id)tracking;
-(void)beginTracking:(id)tracking;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
@end

