/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <Foundation/NSObject.h>

typedef struct {
	BOOL itemIsEnabled[20];
	BOOL timeString[64];
	int gsmSignalStrengthRaw;
	int gsmSignalStrengthBars;
	BOOL serviceString[100];
	BOOL serviceImageBlack[100];
	BOOL serviceImageSilver[100];
	BOOL operatorDirectory[1024];
	unsigned serviceContentType;
	int wifiSignalStrengthRaw;
	int wifiSignalStrengthBars;
	unsigned dataNetworkType;
	int batteryCapacity;
	unsigned batteryState;
	int bluetoothBatteryCapacity;
	int thermalColor;
	unsigned slowActivity : 1;
	BOOL activityDisplayId[256];
	unsigned bluetoothConnected : 1;
	unsigned displayRawGSMSignal : 1;
	unsigned displayRawWifiSignal : 1;
} XXStruct_25kEjA;

@class UIStatusBarItemView, UIStatusBarForegroundView;

__attribute__((visibility("hidden")))
@interface UIStatusBarLayoutManager : NSObject {
@private
	UIStatusBarForegroundView* _foregroundView;
	int _region;
	UIStatusBarItemView* _itemViews[20];
}
@property(assign, nonatomic) UIStatusBarForegroundView* foregroundView;
-(id)initWithRegion:(int)region foregroundView:(id)view;
-(void)dealloc;
-(BOOL)prepareEnabledItems:(BOOL*)items;
-(BOOL)updateItemsWithData:(XXStruct_25kEjA*)data actions:(int)actions animated:(BOOL)animated;
-(void)reflowWithVisibleItems:(id)visibleItems duration:(double)duration;
-(void)removeDisabledItems:(BOOL*)items;
-(void)positionInvisibleItems;
-(void)makeVisibleItemsPerformPendedActions;
-(float)widthNeededForItem:(id)item;
-(float)widthNeededForItems:(id)items;
-(void)clearOverlapFromItems:(id)items;
-(float)distributeOverlap:(float)overlap amongItems:(id)items;
-(float)removeOverlap:(float)overlap fromItems:(id)items;
-(CGRect)rectForItems:(id)items;
-(BOOL)itemIsVisible:(id)visible;
-(void)itemView:(id)view widthChangedBy:(float)by;
-(float)_widthNeededForItemView:(id)itemView;
-(id)_viewForItem:(id)item creatingIfNecessary:(BOOL)necessary;
-(id)_itemViews;
-(id)_itemViewsSortedForLayout;
-(SEL)_itemSortSelector;
-(float)_startPosition;
-(CGRect)_frameForItemView:(id)itemView startPosition:(float)position;
-(float)_positionAfterPlacingItemView:(id)view startPosition:(float)position;
-(CGRect)_repositionedNewFrame:(CGRect)frame widthDelta:(float)delta;
@end

